[[language]]
name = "rust"
auto-format = true

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}
